"$schema" = "https://schemastore.netlify.app/netlify-toml.json?"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[build]
command = "deno upgrade && deno task mkall"
publish = "app/output"

[dev]
port = 1111
targetPort = 1110
command = "deno task dev"
autoLaunch = false
framework = "vite"
