export default {
	base: "vs" as const,
	inherit: true,
	colors: {
		"editor.background": "#fdfeff",
		"editor.foreground": "#086F8A",
	},
	rules: [
		{token: "comment", foreground: "#8899aa", fontStyle: "italic"},
		{token: "invalid.illegal", foreground: "#ff2a50"},
		{token: "keyword", foreground: "#810005"},
		{token: "keyword.operator", foreground: "#086F8A"},
		{token: "constant.language", foreground: "#0CADD6"},
		{token: "constant.numeric", foreground: "#3999FF"},
		{token: "constant.character", foreground: "#3999FF"},
		{token: "constant.character.escape", foreground: "#000000"},
		{token: "constant.other.symbol", foreground: "#208776"},
		{token: "variable.language", foreground: "#ee046f"},
		{token: "variable", foreground: "#ff552a"},
		{token: "variable.other", foreground: "#ff552a"},
		{token: "variable.other.local", foreground: "#ff552a"},
		{token: "variable.other.global", foreground: "#ff552a"},
		{token: "support.class", foreground: "#DB4E80"},
		{token: "support.type", foreground: "#0CADD6"},
		{token: "support.constant", foreground: "#ee046f"},
		{token: "support.function", foreground: "#3999FF"},
		{token: "entity.name.function", foreground: "#3999FF"},
		{token: "entity.name.type", foreground: "#DB4E80"},
		{token: "keyword.operator", foreground: "#086F8A"},
		{token: "keyword", foreground: "#810005"},
		{token: "storage", foreground: "#810005"},
		{token: "constant.language.boolean", foreground: "#208776"},
		{token: "type", foreground: "#0CADD6"},
		{
			token: "constant.language",
			foreground: "#ee046f",
			fontStyle: "bold",
		},
		{token: "string", background: "#B1D5D1", foreground: "#208776"},
	],
}
